# Generated by Django 2.2.10 on 2020-11-09 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('date_activated', models.DateTimeField(blank=True)),
                ('expiration_date', models.DateTimeField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('period', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('contacts_name', models.CharField(blank=True, max_length=255)),
                ('contacts_email', models.CharField(blank=True, max_length=255)),
                ('contacts_phone_number', models.CharField(max_length=20)),
                ('employee_count', models.IntegerField()),
                ('bought_payroll', models.BooleanField(default=True)),
                ('bought_ess', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('blame', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('license_code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='company.License')),
                ('subscription', models.ManyToManyField(to='company.Subscription')),
            ],
        ),
    ]
