# Generated by Django 2.2.10 on 2020-11-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contacts_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription',
            field=models.ManyToManyField(null=True, to='company.Subscription'),
        ),
    ]
