# Generated by Django 2.2.10 on 2020-11-09 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201109_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='company.License'),
        ),
    ]
