# Generated by Django 2.2.10 on 2020-11-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20201109_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='date_activated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
