# Generated by Django 2.2.10 on 2020-11-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20201109_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='subscription',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=555),
        ),
    ]
