# Generated by Django 2.2.10 on 2020-11-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20201111_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='staff_used',
            field=models.IntegerField(null=True),
        ),
    ]
