# Generated by Django 2.2.10 on 2020-11-21 12:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_company_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_month', models.IntegerField()),
                ('previous_year', models.IntegerField()),
                ('previous_employee_count', models.IntegerField()),
                ('previous_ess', models.BooleanField()),
                ('new_month', models.IntegerField()),
                ('new_year', models.IntegerField()),
                ('new_employee_count', models.IntegerField()),
                ('new_ess', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_month',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_year',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Company'),
        ),
    ]
