/**
 * User Actions
 * Object
 */
const UserActions = {
	SIGN_IN: 'SIGN_IN',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	SIGN_IN_FAIL: 'SIGN_IN_FAIL',
	SIGN_OUT: 'SIGN_OUT',
	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
	SIGN_OUT_FAIL: 'SIGN_OUT_FAIL',
	RESET_PASSWORD: 'RESET_PASSWORD',
	RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
	RESET_PASSWORD_FAIL: 'RESET_PASSWORD_FAIL',
	FORGOT_PASSWORD: 'FORGOT_PASSWORD',
	FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
	GET_USER: 'GET_USER',
	GET_USER_ERROR: 'GET_USER_ERROR',
	ACTIVATE_LICENSE: 'ACTIVATE_LICENSE',
	GET_USER_ACCESS: 'GET_USER_ACCESS',
	CREATE_USER_ACCESS: 'CREATE_USER_ACCESS',
	EDIT_USER_ACCESS: 'EDIT_USER_ACCESS',
};

export default UserActions;
