# Generated by Django 2.2.10 on 2020-11-12 23:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselog',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
