# Generated by Django 2.2.10 on 2020-11-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20201121_1336'),
        ('auditlog', '0003_auto_20201121_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylog',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='baselog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('CHANGE', 'Change')], max_length=10),
        ),
    ]
