# Generated by Django 2.2.10 on 2020-12-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0004_auto_20201123_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companylog',
            name='previous',
        ),
    ]
