# Generated by Django 2.2.10 on 2021-12-22 19:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_holiday'),
        ('accounts', '0002_auto_20211220_2027'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollCategory',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='company.CompanyPolicy')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.AdminUser')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PayrollElements',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mandatory', models.BooleanField(blank=True, default=False, null=True)),
                ('prorata', models.BooleanField(blank=True, default=False, null=True)),
                ('prorata_value', models.CharField(blank=True, max_length=255, null=True)),
                ('calculation_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed'), ('CUSTOM', 'Custom'), ('NONE', 'None'), ('EMPLOYEE_DRIVEN', 'Employee Driven')], default='NONE', max_length=30, null=True)),
                ('calculation_type_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_query', models.TextField(blank=True)),
                ('earning_type', models.CharField(blank=True, choices=[('PENSIONABLE', 'Pensionable'), ('TAXABLE', 'Taxable'), ('NON_TAXABLE', 'Non Taxable')], max_length=30, null=True)),
                ('when_to_pay', models.CharField(blank=True, choices=[('BIRTHDAY', 'Birthday'), ('ALWAYS', 'Always'), ('DATE_ENGAGED', 'Date Engaged'), ('CUSTOM', 'Custom Month')], max_length=30, null=True)),
                ('when_to_pay_months', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, null=True, size=None)),
                ('element_type', models.CharField(blank=True, choices=[('EARNINGS', 'Earnings'), ('DEDUCTIONS', 'Deductions'), ('COMPANY_CONTRIBUTION', 'Company Contribution'), ('FRINGE_BENEFIT', 'Fringe Benefit'), ('PROVISIONS', 'Provisions'), ('ADDITIONS', 'Additions')], max_length=30, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.PayrollCategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.AdminUser')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
