# Generated by Django 2.2.10 on 2021-12-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_pensionsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionsettings',
            name='payroll_lines',
            field=models.ManyToManyField(to='payroll.PayrollElements'),
        ),
        migrations.AlterField(
            model_name='taxrelief',
            name='payroll_lines',
            field=models.ManyToManyField(to='payroll.PayrollElements'),
        ),
    ]
