# Generated by Django 2.2.10 on 2021-12-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20211223_0104'),
        ('payroll', '0007_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDrivenPayroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.Employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.PayrollElements')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
