# Generated by Django 2.2.10 on 2021-12-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_employeetaxrelief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrelief',
            name='payroll_lines',
            field=models.ManyToManyField(blank=True, to='payroll.PayrollElements'),
        ),
    ]
