/**
 * Accounts Actions
 * Object
 */
const AccountsActions = {
	CREATE_STAFF: 'CREATE_STAFF',
	EDIT_STAFF: 'EDIT_STAFF',
	CREATE_COMPANY: 'CREATE_COMPANY',
	DELETE_COMPANY: 'DELETE_COMPANY',
	EDIT_COMPANY: 'EDIT_COMPANY',
	GET_COMPANY: 'GET_COMPANY',
	GET_COMPANY_AUDIT: 'GET_COMPANY_AUDIT',
	GET_STAFF_AUDIT: 'GET_STAFF_AUDIT',
	GET_STAFF: 'GET_STAFF',
	GET_COMPANY_BY_ID: 'GET_COMPANY_BY_ID',
	GET_AUDIT_LOG: 'GET_AUDIT_LOG',
};

export default AccountsActions;
