# Generated by Django 2.2.10 on 2021-12-22 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0005_pensionsettings'),
        ('company', '0008_auto_20211222_2336'),
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('other_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('SINGLE', 'Single'), ('WIDOWED', 'Widowed')], max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email address')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='accounts')),
                ('activation_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('employee_code', models.CharField(blank=True, max_length=255, null=True)),
                ('date_engaged', models.DateField(blank=True, null=True)),
                ('probation_period', models.IntegerField(blank=True, null=True)),
                ('pension_pin', models.CharField(blank=True, max_length=50)),
                ('pension_start_date', models.DateField(blank=True, null=True)),
                ('tax_identification_number', models.CharField(blank=True, max_length=50)),
                ('nhf', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=75, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=75, null=True)),
                ('next_of_kin_phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('next_of_kin_email', models.CharField(blank=True, max_length=75, null=True)),
                ('account_number', models.CharField(blank=True, max_length=15)),
                ('account_name', models.CharField(blank=True, max_length=80)),
                ('fixed_tax', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('hours_per_day', models.IntegerField(blank=True, null=True)),
                ('hours_per_week', models.IntegerField(blank=True, null=True)),
                ('hours_per_month', models.IntegerField(blank=True, null=True)),
                ('rates_per_hour', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('rates_per_day', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('rates_per_month', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('rates_per_year', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('pension_applied', models.BooleanField(default=False)),
                ('tax_applied', models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('FIXED', 'fixed')], default='NO', max_length=10)),
                ('works_monday', models.BooleanField(default=True)),
                ('works_tuesday', models.BooleanField(default=True)),
                ('works_wednesday', models.BooleanField(default=True)),
                ('works_thursday', models.BooleanField(default=True)),
                ('works_friday', models.BooleanField(default=True)),
                ('works_saturday', models.BooleanField(default=False)),
                ('works_sunday', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated'), ('REINSTATED', 'Reinstated'), ('PENDING', 'Pending'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', max_length=20)),
                ('terminated_date', models.DateField(null=True)),
                ('reinstated_date', models.DateField(null=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_root_user', models.BooleanField(default=False, verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='utilities.BankLists')),
                ('company_policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_policy', to='company.CompanyPolicy')),
                ('hierarchy', models.ManyToManyField(null=True, related_name='employee_hierarchy', to='company.Hierarchy')),
                ('job_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='utilities.JobGrade')),
                ('job_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='utilities.JobTitle')),
                ('leaves', models.ManyToManyField(null=True, related_name='employee_hierarchy', to='company.Leave')),
                ('main_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_user', to='company.Company')),
                ('nature_of_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='utilities.ContractNature')),
                ('reinstate_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='utilities.ReinstateReason')),
                ('remuneration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_remuneration', to='payroll.Remuneration')),
                ('tax_relief', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_taxrelief', to='payroll.TaxReliefGroup')),
                ('terminate_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='utilities.TerminateReason')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
