/**
 * Actions
 * Object
 */
const LeaveStructure = {
	ADD_LEAVE: 'ADD_LEAVE',
	ADD_CATEGORY: 'ADD_CATEGORY',
	GET_LEAVE: 'GET_LEAVE',
	DEACTIVATE_LEAVE: 'DEACTIVATE_LEAVE',
	DEACTIVATE_CATEGORY: 'DEACTIVATE_CATEGORY',
	EDIT_LEAVE: 'EDIT_LEAVE',
	GET_BY_ID: 'GET_BY_ID',
	GET_CATEGORY: 'GET_CATEGORY',
	EDIT_CATEGORY: 'EDIT_CATEGORY',
	GET_EMPLOYEE_AVAILABLE_LEAVE: 'GET_EMPLOYEE_AVAILABLE_LEAVE',
	SAVE_EMPLOYEE_WORKFLOW_LEAVE: 'SAVE_EMPLOYEE_WORKFLOW_LEAVE',
	GET_EMPLOYEE_LEAVE_REQUEST: 'GET_EMPLOYEE_LEAVE_REQUEST',
	APPROVE_REJECT_LEAVE_REQUEST: 'APPROVE_REJECT_LEAVE_REQUEST',
	GET_ERROR: 'GET_ERROR',
};

export default LeaveStructure;
