/**
 * Actions
 * Object
 */
const SettingsStructure = {
	ADD_BANK: 'ADD_BANK',
	GET_BANKS: 'GET_BANKS',
	DEACTIVATE_BANK: 'DEACTIVATE_BANK',
	EDIT_BANK: 'EDIT_BANK',
	ADD_JOB_TITLE: 'ADD_JOB_TITLE',
	GET_JOB_TITLES: 'GET_JOB_TITLES',
	DEACTIVATE_JOB_TITLE: 'DEACTIVATE_JOB_TITLE',
	EDIT_JOB_TITLE: 'EDIT_JOB_TITLE',
	ADD_TERMINATE_REASON: 'ADD_TERMINATE_REASON',
	GET_TERMINATE_REASON: 'GET_TERMINATE_REASON',
	DEACTIVATE_TERMINATE_REASON: 'DEACTIVATE_TERMINATE_REASON',
	EDIT_TERMINATE_REASON: 'EDIT_TERMINATE_REASON',
	ADD_REINSTATE_REASON: 'ADD_REINSTATE_REASON',
	GET_REINSTATE_REASON: 'GET_REINSTATE_REASON',
	DEACTIVATE_REINSTATE_REASON: 'DEACTIVATE_REINSTATE_REASON',
	EDIT_REINSTATE_REASON: 'EDIT_REINSTATE_REASON',
	ADD_NATURE_OF_CONTRACT: 'ADD_NATURE_OF_CONTRACT',
	GET_NATURE_OF_CONTRACTS: 'GET_NATURE_OF_CONTRACTS',
	DEACTIVATE_NATURE_OF_CONTRACT: 'DEACTIVATE_NATURE_OF_CONTRACT',
	EDIT_NATURE_OF_CONTRACT: 'EDIT_NATURE_OF_CONTRACT',
	ADD_JOB_GRADE: 'ADD_JOB_GRADE',
	GET_JOB_GRADES: 'GET_JOB_GRADES',
	DEACTIVATE_JOB_GRADES: 'DEACTIVATE_JOB_GRADES',
	EDIT_JOB_GRADES: 'EDIT_JOB_GRADES',
	ADD_PENSION_SETTINGS: 'ADD_PENSION_SETTINGS',
	GET_PENSION_SETTINGS: 'GET_PENSION_SETTINGS',
	GET_ERROR: 'GET_ERROR',
};

export default SettingsStructure;
