/**
 * Actions
 * Object
 */
const EmployeeStructure = {
	ADD_EMPLOYEE: 'ADD_EMPLOYEE',
	GET_EMPLOYEES: 'GET_EMPLOYEES',
	GET_EMPLOYEE: 'GET_EMPLOYEE',
	DEACTIVATE_EMPLOYEE: 'DEACTIVATE_EMPLOYEE',
	EDIT_EMPLOYEE: 'EDIT_EMPLOYEE',
	GET_EMPLOYEE_PAYSLIP: 'GET_EMPLOYEE_PAYSLIP',
	DOWNLOAD_PAYSLIP: 'DOWNLOAD_PAYSLIP',
	SEND_INVITATION: 'SEND_INVITATION',
	GET_ERROR: 'GET_ERROR',
};

export default EmployeeStructure;
