/**
 * Actions
 * Object
 */
const PayrollStructure = {
	ADD_PAYROLL: 'ADD_PAYROLL',
	ADD_CATEGORY: 'ADD_CATEGORY',
	GET_PAYROLL: 'GET_PAYROLL',
	DEACTIVATE_PAYROLL: 'DEACTIVATE_PAYROLL',
	DEACTIVATE_CATEGORY: 'DEACTIVATE_CATEGORY',
	EDIT_PAYROLL: 'EDIT_PAYROLL',
	GET_BY_ID: 'GET_BY_ID',
	GET_CATEGORY: 'GET_CATEGORY',
	EDIT_CATEGORY: 'EDIT_CATEGORY',
	ADD_REMUNERATION: 'ADD_REMUNERATION',
	GET_REMUNERATION: 'GET_REMUNERATION',
	GET_REMUNERATION_BY_ID: 'GET_REMUNERATION_BY_ID',
	EDIT_REMUNERATION: 'EDIT_REMUNERATION',
	GET_PAY_PERIOD: 'GET_PAY_PERIOD',
	ACTIVATE_PAY_PERIOD: 'ACTIVATE_PAY_PERIOD',
	GET_BANK_LETTER: 'GET_BANK_LETTER',
	ADD_TRANSACTION: 'ADD_TRANSACTION',
	GET_TRANSACTION: 'GET_TRANSACTION',
	GET_EMPLOYEE_DRIVEN_TAX: 'GET_EMPLOYEE_DRIVEN_TAX',
	ADD_EMPLOYEE_DRIVEN_TAX: 'ADD_EMPLOYEE_DRIVEN_TAX',
	GET_PAYROLL_READY_FOR_TRANSACTION: 'GET_PAYROLL_READY_FOR_TRANSACTION',
	GET_EMPLOYEE_DRIVEN_PAYROLL: 'GET_EMPLOYEE_DRIVEN_PAYROLL',
	ADD_EMPLOYEE_DRIVEN_PAYROLL: 'ADD_EMPLOYEE_DRIVEN_PAYROLL',
	GET_LOANS: 'GET_LOANS',
	ADD_LOAN: 'ADD_LOAN',
	EDIT_LOAN: 'EDIT_LOAN',
	DEACTIVATE_LOAN: 'DEACTIVATE_LOAN',
	GET_ERROR: 'GET_ERROR',
};

export default PayrollStructure;
