/**
 * Actions
 * Object
 */
const CompanyPolicyStructure = {
	ADD_COMPANY_POLICY: 'ADD_COMPANY_POLICY',
	GET_COMPANY_POLICY: 'GET_COMPANY_POLICY',
	EDIT_COMPANY_POLICY: 'EDIT_COMPANY_POLICY',
	DEACTIVATE_COMPANY_POLICY: 'DEACTIVATE_COMPANY_POLICY',
	ADD_HOLIDAYS: 'ADD_HOLIDAYS',
	GET_HOLIDAYS: 'GET_HOLIDAYS',
	EDIT_HOLIDAYS: 'EDIT_HOLIDAYS',
	DEACTIVATE_HOLIDAYS: 'DEACTIVATE_HOLIDAYS',
	ADD_TAX_TABLE: 'ADD_TAX_TABLE',
	GET_TAX_TABLE: 'GET_TAX_TABLE',
	EDIT_TAX_TABLE: 'EDIT_TAX_TABLE',
	DEACTIVATE_TAX_TABLE: 'DEACTIVATE_TAX_TABLE',
	GET_PAY_PERIOD: 'GET_PAY_PERIOD',
	GET_BY_ID: 'GET_BY_ID',
	GET_ERROR: 'GET_ERROR',
};

export default CompanyPolicyStructure;
