/**
 * Actions
 * Object
 */
const TaxManagementActions = {
	ADD_TAX_RELIEF_GROUP: 'ADD_TAX_RELIEF_GROUP',
	GET_TAX_RELIEF_GROUP: 'GET_TAX_RELIEF_GROUP',
	EDIT_TAX_RELIEF_GROUP: 'EDIT_TAX_RELIEF_GROUP',
	DEACTIVATE_TAX_RELIEF_GROUP: 'DEACTIVATE_TAX_RELIEF_GROUP',

	ADD_TAX_RELIEF: 'ADD_TAX_RELIEF',
	GET_TAX_RELIEF: 'GET_TAX_RELIEF',
	EDIT_TAX_RELIEF: 'EDIT_TAX_RELIEF',
	DEACTIVATE_TAX_RELIEF: 'DEACTIVATE_TAX_RELIEF',
	GET_ERROR: 'GET_ERROR',
};

export default TaxManagementActions;
