# Generated by Django 2.2.10 on 2021-12-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidiaryLog',
            fields=[
                ('baselog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auditlog.BaseLog')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
            ],
            bases=('auditlog.baselog',),
        ),
    ]
