# Generated by Django 2.2.10 on 2021-12-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_subsidiarylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPolicyLog',
            fields=[
                ('baselog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auditlog.BaseLog')),
            ],
            bases=('auditlog.baselog',),
        ),
    ]
