# Generated by Django 2.2.10 on 2021-12-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0004_companypolicylog_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCategoryLog',
            fields=[
                ('baselog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auditlog.BaseLog')),
            ],
            bases=('auditlog.baselog',),
        ),
        migrations.CreateModel(
            name='LeaveLog',
            fields=[
                ('baselog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auditlog.BaseLog')),
            ],
            bases=('auditlog.baselog',),
        ),
    ]
