# Generated by Django 2.2.10 on 2021-12-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_leave_leavecategory'),
        ('auditlog', '0005_leavecategorylog_leavelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavelog',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Leave'),
        ),
        migrations.AddField(
            model_name='leavecategorylog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.LeaveCategory'),
        ),
    ]
