# Generated by Django 2.2.10 on 2021-12-22 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0007_hierarchylog'),
        ('company', '0006_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchylog',
            name='hierarchy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Hierarchy'),
        ),
    ]
