# Generated by Django 2.2.10 on 2021-12-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0009_holidaylog'),
        ('company', '0007_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaylog',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Holiday'),
        ),
    ]
