# Generated by Django 2.2.10 on 2021-12-22 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_holiday'),
        ('auditlog', '0010_holidaylog_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollCategoryLog',
            fields=[
                ('baselog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auditlog.BaseLog')),
            ],
            bases=('auditlog.baselog',),
        ),
        migrations.CreateModel(
            name='PayrollElementLog',
            fields=[
                ('baselog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auditlog.BaseLog')),
            ],
            bases=('auditlog.baselog',),
        ),
        migrations.CreateModel(
            name='TaxTableLog',
            fields=[
                ('baselog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auditlog.BaseLog')),
                ('tax_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.TaxTable')),
            ],
            bases=('auditlog.baselog',),
        ),
    ]
