# Generated by Django 2.2.10 on 2021-12-22 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollcategory_payrollelements'),
        ('auditlog', '0011_payrollcategorylog_payrollelementlog_taxtablelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollelementlog',
            name='payroll_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.PayrollElements'),
        ),
        migrations.AddField(
            model_name='payrollcategorylog',
            name='payroll_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.PayrollCategory'),
        ),
    ]
