# Generated by Django 2.2.10 on 2021-12-20 19:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('bought_payroll', models.BooleanField(default=True)),
                ('bought_ess', models.BooleanField(default=False)),
                ('employee_count', models.IntegerField(default=0)),
                ('subscription_expiration_date', models.DateTimeField(null=True)),
                ('subscription_year', models.IntegerField(default=0)),
                ('subscription_month', models.IntegerField(default=0)),
                ('license_code', models.CharField(max_length=255, null=True)),
                ('middleware_id', models.UUIDField(null=True)),
                ('middleware_date_activated', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_subsidiary', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.AdminUser')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subsidiary_created_by', to='accounts.AdminUser')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
