# Generated by Django 2.2.10 on 2021-12-22 11:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211220_2027'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPolicy',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_cycle', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=50)),
                ('works_monday', models.BooleanField(default=False)),
                ('works_tuesday', models.BooleanField(default=False)),
                ('works_wednesday', models.BooleanField(default=False)),
                ('works_thursday', models.BooleanField(default=False)),
                ('works_friday', models.BooleanField(default=False)),
                ('works_saturday', models.BooleanField(default=False)),
                ('works_sunday', models.BooleanField(default=False)),
                ('statutory_tax_year_start', models.DateTimeField(blank=True)),
                ('statutory_tax_year_end', models.DateTimeField(blank=True)),
                ('probation_months', models.IntegerField(default=0)),
                ('hours_per_week', models.IntegerField(default=0)),
                ('hours_per_day', models.IntegerField(default=0)),
                ('hours_per_month', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ManyToManyField(related_name='policy_company', to='company.Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_created_by', to='accounts.AdminUser')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
