# Generated by Django 2.2.10 on 2021-12-22 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211220_2027'),
        ('company', '0002_companypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxTable',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('income_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('company_policy', models.ManyToManyField(related_name='tax_table_policy', to='company.CompanyPolicy')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tax_table_created_by', to='accounts.AdminUser')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
