# Generated by Django 2.2.10 on 2021-12-20 19:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsBaseModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='BankLists',
            fields=[
                ('settingsbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilities.SettingsBaseModel')),
                ('bank_code', models.CharField(blank=True, max_length=255)),
                ('sort_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('utilities.settingsbasemodel',),
        ),
        migrations.CreateModel(
            name='ContractNature',
            fields=[
                ('settingsbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilities.SettingsBaseModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('utilities.settingsbasemodel',),
        ),
        migrations.CreateModel(
            name='JobGrade',
            fields=[
                ('settingsbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilities.SettingsBaseModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('utilities.settingsbasemodel',),
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('settingsbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilities.SettingsBaseModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('utilities.settingsbasemodel',),
        ),
        migrations.CreateModel(
            name='ReinstateReason',
            fields=[
                ('settingsbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilities.SettingsBaseModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('utilities.settingsbasemodel',),
        ),
        migrations.CreateModel(
            name='TerminateReason',
            fields=[
                ('settingsbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilities.SettingsBaseModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('utilities.settingsbasemodel',),
        ),
    ]
